modLoader="javafml"
loaderVersion="[37,)"
license="${license}"
[[mods]]
    modId="${id}"
    version="${version}"
    displayName="${name}"
    authors="${authors}"
    description='''${description}'''
    logoFile="icon.png"
[[dependencies.${id}]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.${id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17,)"
    ordering="NONE"
    side="BOTH"